# Generated by Django 5.2.4 on 2025-07-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("genre", models.JSONField(default=list)),
                ("year", models.PositiveIntegerField()),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("is_adult", models.BooleanField(default=False)),
            ],
        ),
    ]
